/**
 * Theme definitions for dp.
 * Each theme is a map of CSS custom property names to values.
 * Applied to document.documentElement.style by ThemeProvider.
 */

export const THEMES = {
  "midnight-terminal": {
    name: "Midnight Terminal",
    description: "Green-on-black terminal aesthetic",
    dark: true,
    vars: {
      "--dp-bg": "#0c0e14",
      "--dp-bg-secondary": "#11131a",
      "--dp-bg-tertiary": "#0a0c11",
      "--dp-border": "#1a1e2e",
      "--dp-border-light": "#252a3a",
      "--dp-text": "#c8cdd8",
      "--dp-text-secondary": "#636b80",
      "--dp-text-dim": "#3a4058",
      "--dp-accent": "#6ee7b7",
      "--dp-green": "#34d399",
      "--dp-green-border": "#4ade80",
      "--dp-red": "#fb7185",
      "--dp-yellow": "#fbbf24",
      "--dp-purple": "#a78bfa",
      "--dp-font": "'IBM Plex Sans', -apple-system, BlinkMacSystemFont, sans-serif",
      "--dp-font-mono": "'IBM Plex Mono', 'Fira Code', monospace",
      "--dp-radius": "4px",
      "--dp-radius-lg": "6px",
      "--dp-btn-bg": "#1a1e2e",
      "--dp-btn-border": "#252a3a",
    },
  },
  "paper-light": {
    name: "Paper Light",
    description: "Warm editorial light theme",
    dark: false,
    vars: {
      "--dp-bg": "#faf8f5",
      "--dp-bg-secondary": "#f0ece6",
      "--dp-bg-tertiary": "#fff",
      "--dp-border": "#ddd7cc",
      "--dp-border-light": "#ccc5b8",
      "--dp-text": "#2c2418",
      "--dp-text-secondary": "#8a7e6e",
      "--dp-text-dim": "#b8ad9c",
      "--dp-accent": "#c45d3e",
      "--dp-green": "#558b44",
      "--dp-green-border": "#6aa858",
      "--dp-red": "#c44040",
      "--dp-yellow": "#b08825",
      "--dp-purple": "#7c5ab8",
      "--dp-font": "'Crimson Pro', 'Source Serif 4', Georgia, serif",
      "--dp-font-mono": "'JetBrains Mono', 'Fira Code', monospace",
      "--dp-radius": "2px",
      "--dp-radius-lg": "4px",
      "--dp-btn-bg": "#ebe5dc",
      "--dp-btn-border": "#ddd7cc",
    },
  },
  "electric": {
    name: "Electric",
    description: "Modern indigo-accented dark theme",
    dark: true,
    vars: {
      "--dp-bg": "#09090b",
      "--dp-bg-secondary": "#121216",
      "--dp-bg-tertiary": "#0d0d10",
      "--dp-border": "#1f1f2e",
      "--dp-border-light": "#2a2a3e",
      "--dp-text": "#e4e4f0",
      "--dp-text-secondary": "#6b6b8a",
      "--dp-text-dim": "#3d3d55",
      "--dp-accent": "#818cf8",
      "--dp-green": "#4ade80",
      "--dp-green-border": "#5eead4",
      "--dp-red": "#f87171",
      "--dp-yellow": "#facc15",
      "--dp-purple": "#c084fc",
      "--dp-font": "'Sora', -apple-system, BlinkMacSystemFont, sans-serif",
      "--dp-font-mono": "'Fira Code', monospace",
      "--dp-radius": "8px",
      "--dp-radius-lg": "12px",
      "--dp-btn-bg": "#1f1f2e",
      "--dp-btn-border": "#2a2a3e",
    },
  },
  "nordic-frost": {
    name: "Nordic Frost",
    description: "Cool professional slate-blue light theme",
    dark: false,
    vars: {
      "--dp-bg": "#e8ecf1",
      "--dp-bg-secondary": "#dce2e9",
      "--dp-bg-tertiary": "#f2f4f7",
      "--dp-border": "#c4cdd8",
      "--dp-border-light": "#b4bfcc",
      "--dp-text": "#1e2a3a",
      "--dp-text-secondary": "#5a6a7e",
      "--dp-text-dim": "#94a3b8",
      "--dp-accent": "#2563eb",
      "--dp-green": "#16a34a",
      "--dp-green-border": "#22c55e",
      "--dp-red": "#dc2626",
      "--dp-yellow": "#ca8a04",
      "--dp-purple": "#7c3aed",
      "--dp-font": "'Manrope', 'Outfit', -apple-system, BlinkMacSystemFont, sans-serif",
      "--dp-font-mono": "'JetBrains Mono', monospace",
      "--dp-radius": "6px",
      "--dp-radius-lg": "10px",
      "--dp-btn-bg": "#dce2e9",
      "--dp-btn-border": "#c4cdd8",
    },
  },
  "ember": {
    name: "Ember",
    description: "Warm dark theme with amber highlights",
    dark: true,
    vars: {
      "--dp-bg": "#140e0a",
      "--dp-bg-secondary": "#1c1410",
      "--dp-bg-tertiary": "#110c08",
      "--dp-border": "#2e2218",
      "--dp-border-light": "#3d2e20",
      "--dp-text": "#e8ddd0",
      "--dp-text-secondary": "#8a7560",
      "--dp-text-dim": "#4e3d2e",
      "--dp-accent": "#f59e0b",
      "--dp-green": "#84cc16",
      "--dp-green-border": "#a3e635",
      "--dp-red": "#ef4444",
      "--dp-yellow": "#eab308",
      "--dp-purple": "#d97706",
      "--dp-font": "'DM Sans', -apple-system, BlinkMacSystemFont, sans-serif",
      "--dp-font-mono": "'Space Mono', monospace",
      "--dp-radius": "3px",
      "--dp-radius-lg": "5px",
      "--dp-btn-bg": "#2e2218",
      "--dp-btn-border": "#3d2e20",
    },
  },
  "corporate": {
    name: "Corporate",
    description: "Deliberately vanilla, muted blue, zero personality",
    dark: false,
    vars: {
      "--dp-bg": "#f5f5f5",
      "--dp-bg-secondary": "#eaeaea",
      "--dp-bg-tertiary": "#fff",
      "--dp-border": "#d4d4d4",
      "--dp-border-light": "#c0c0c0",
      "--dp-text": "#333",
      "--dp-text-secondary": "#777",
      "--dp-text-dim": "#aaa",
      "--dp-accent": "#4a7cbc",
      "--dp-green": "#5a9a5a",
      "--dp-green-border": "#6ab06a",
      "--dp-red": "#c05050",
      "--dp-yellow": "#b09030",
      "--dp-purple": "#7868a8",
      "--dp-font": "'Segoe UI', -apple-system, BlinkMacSystemFont, sans-serif",
      "--dp-font-mono": "Consolas, 'Courier New', monospace",
      "--dp-radius": "4px",
      "--dp-radius-lg": "6px",
      "--dp-btn-bg": "#e0e0e0",
      "--dp-btn-border": "#d4d4d4",
    },
  },
};

export const DEFAULT_THEME = "midnight-terminal";

export function getThemeIds() {
  return Object.keys(THEMES);
}

export function getTheme(id) {
  return THEMES[id] || THEMES[DEFAULT_THEME];
}
